### ISSUE TITLE
DB file

### ISSUE THREAD

**Issue by thant-sin-aung** [shakeelosmani/MvcAffableBean#3]
I cannot find database file of this project. How can I find it? Please, advise me. Thanks.

**Comment by abishek06** [comment]
IN app data it will be. If is not showing, select App Data folder and in top above the Project you will find a option called "show all files". Select it.

**Comment by Nerd87** [comment]
Hi I've follow your instructions to find DB but I can't find it! My AppData folder is empty! Can you send me a zip with db?  This my mail: andr3ap@gmail.com

Thanks in advance

**Comment by shakeelosmani** [comment]
There are two types of database in the project. Both will be created once you run the project. The app_data one is created by ASP.net Identity service to store user information. If you use a localdb instance for the db context as well then another db file will be created storing the ecommerce tables. If you use sql server then it will create the tables in you sql server database. But you will see both only after you run the application. This is codefirst development so there is no database created till you run the application

**Comment by Nerd87** [comment]
If I try to run application exception occurred:

 'FK_dbo.OrderedProducts_dbo.Products_ProductId' refers to invalid table 'dbo.Products'.

**Comment by shakeelosmani** [comment]
Follow the steps mentioned in the Blog here:

https://shakeelosmani.wordpress.com/2015/12/27/asp-net-mvc-step-by-step-complete-e-commerce-tutorial/

Look for a section called ***update***

To fix this problem

**Comment by Nerd87** [comment]
You are great! Thank you very much!!!

**Comment by shakeelosmani** [comment]
Glad that it helped. This issue is now closed!
